from pydantic import BaseModel, ConfigDict, Field
from typing import List, Optional

class ChatRequestSchema(BaseModel):
    session_id: str = Field(description="Unique identifier for the user session")
    message: str = Field(description="The latest message from the user")

class ChatResponseSchema(BaseModel):
    session_id: str = Field(description="Unique identifier for the user session")
    reply: str = Field(description="The natural language explanation generated by the Agent")
    recommendations: List[dict] = Field(
        default_factory=list,
        description="Ranked college program recommendations generated by the backend engine"
    )
