"""Add chat messages table

Revision ID: 1c26e9f9d3c2
Revises: f4c2d7e9b3a1
Create Date: 2026-03-16 05:14:30.123195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c26e9f9d3c2'
down_revision: Union[str, Sequence[str], None] = 'f4c2d7e9b3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decision_programs', type_='foreignkey')
    op.create_foreign_key(None, 'decision_programs', 'decision_colleges', ['college_id'], ['id'])
    op.drop_constraint(None, 'decision_program_traits', type_='foreignkey')
    op.create_foreign_key(None, 'decision_program_traits', 'decision_programs', ['program_id'], ['id'])
    op.drop_constraint(None, 'decision_program_decision_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'decision_program_decision_profiles', 'decision_programs', ['program_id'], ['id'])
    op.drop_constraint(None, 'decision_program_career_paths', type_='foreignkey')
    op.create_foreign_key(None, 'decision_program_career_paths', 'decision_programs', ['program_id'], ['id'])
    op.drop_constraint(None, 'decision_employment_outlooks', type_='foreignkey')
    op.create_foreign_key(None, 'decision_employment_outlooks', 'decision_programs', ['program_id'], ['id'])
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
