"""initial schema

Revision ID: 3d6b8e491c76
Revises: 
Create Date: 2026-02-01 15:17:47.976219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6b8e491c76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('governorate', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colleges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vision', sa.Text(), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('parent_institution', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campus_colleges',
    sa.Column('campus_id', sa.String(length=36), nullable=False),
    sa.Column('college_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('campus_id', 'college_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('college_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('discipline', sa.String(length=100), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('teaching_language', sa.String(length=50), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('certificate_types', sa.JSON(), nullable=False),
    sa.Column('mandatory_subjects', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuition_fees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=1), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('per_semester', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuition_fees')
    op.drop_table('programs')
    op.drop_table('campus_colleges')
    op.drop_table('colleges')
    op.drop_table('campuses')
    # ### end Alembic commands ###
